server:
  port: 7088

spring:
  application:
    name: order-service
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    url: jdbc:mysql://47.95.207.217:3306/jmyz?zeroDateTimeBehavior=convertToNull&zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=utf-8
    username: root
    password: jmyz-123456
  redis:
    database: 0
    host: 192.168.1.6
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

# mybatis配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sso.model
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
      logic-delete-value: -1
      logic-not-delete-value: 100
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false #配置的缓存的全局开关
    lazyLoadingEnabled: false #延时加载的开关
    multipleResultSetsEnabled: false #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5011/eureka/
    fetch-registry: true
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true

logging:
  config: classpath:logback-spring.xml

rocketmq:
  nameServer: 192.168.1.10:9876
  producer:
    group: my-group1
    send-message-timeout: 300000

demo:
  rocketmq:
    topic: string-topic